---
title: "p8105_hw5_yj2580"
author: "yj2580"
date: "11/5/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(ggplot2)

set.seed(10)
```

## Problem 1

```{r}
iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

fill_value = function(x) {
  if(is.character(x)) {
   x = replace_na(x, "virginica")
  } else if(is.numeric(x)){
   mean = round(mean(x, na.rm = TRUE),1)
   x = replace_na(x, mean)
  }
}
iris_new = map_dfr(iris_with_missing, fill_value)
```

## Problem 2

```{r}
list1 = list.files(path = "data")
data = purrr::map_dfr(str_c("./data/", list1), read_csv) %>%
  mutate(name = list1, 
         name = str_replace(name, ".csv", "")
  ) %>%
  separate(name, into = c("arm", "id"), sep = "_") %>%
  mutate(arm = factor(arm), 
         id = factor(id)) %>%
  select(arm, id, everything()) %>%
  pivot_longer(week_1:week_8,
              names_to = "week",
              names_prefix = "week_",
              values_to = "observation")

data %>%
  group_by(id) %>%
  ggplot(aes(x = week, y = observation, colour = id, group = id)) +
  geom_point() +
  geom_line() + 
  facet_grid(.~arm) +
  labs(title = "Observations on each subject over time in different groups")
```

Comment: Compared with the control arm group, there is an obviously increasing trend of observation in the experiment arm group. Overall, the average values of observations are higher in the experiment arm group.

## Problem 3

```{r}
sim_regression = function(beta1, n = 30, beta0 = 2) {
  sim_data = tibble(
    x = rnorm(n, mean = 0, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, sqrt(50))
  )
  
  ls_fit = lm(y ~ x, data = sim_data) %>%
    broom::tidy() %>%
    filter(term == "x") %>%
    select(estimate, p.value) %>%
    rename(beta1_hat = estimate,
           p_value = p.value)
}
  
output = vector("list", 10000)

for (i in 1:10000) {
  output[[i]] = sim_regression(beta1 = 0)
}

sim_results = bind_rows(output)
```

```{r}

```

